export const users = {
    accountId: 121,
    addressId: null,
    blockReporting: false,
    calculationType: "count_own_work",
    changedBy: 11711,
    comment: "",
    contractNumber: "",
    currencyId: 1,
    documentRoot: "",
    endOfContract: null,
    expectedAddedValue: null,
    expectedAddedValueHours: null,
    expectedContractValue: null,
    expectedMargin: null,
    expectedOwnWork: null,
    expectedSubdeliveries: null,
    expectedValue: null,
    finishTime: null,
    finished: false,
    finishedBy: null,
    firmId: 34,
    forceAllocationsOnDefinedWorkTypeOnly: false,
    id: 16781,
    name: "Produkt 2024",
    onlyReportOnAllocations: false,
    organizationalUnitId: 1,
    ownNumber: null,
    parentId: null,
    proposedAccount: null,
    realisation: true,
    realisationDate: null,
    realisationProbability: null,
    reportingBlockedChangedAt: null,
    reportingBlockedChangedBy: null,
    reportingBlockedToIncl: null,
    setUpBy: 11711,
    setUpTime: "2024-01-03 08:46:52",
    timeOfChange: "2024-01-03 08:46:52",
    workReportingCannotExceedAllocationPlan: false,
    workReportsOnlyOnDefinedWorkTypes: false
}